### ISSUE TITLE
Video embed returns blank screen behind proxy.

### ISSUE THREAD

**Issue by TerakoyaAcademia** [mattermost/mattermost-plugin-oembed#10]
Hello! I am using the  mattermost-plugin-oembed in my mattermost server. I have deployed the mattermost behind the corporate proxy using the docker file. In the mattermost, Before i install (or disable) this plugin, I can see the video information of respective video like below: 
![image](https://user-images.githubusercontent.com/85092129/141967583-1214bb12-1092-404c-8af0-5551511c83ae.png)

But when i enable the plugin, blank screen is displayed as shown below: 
![image](https://user-images.githubusercontent.com/85092129/141967672-14a00239-59d9-40d5-9100-3176867f0603.png)

When i share YouTube link, the video preview is available as shown below: 
![image](https://user-images.githubusercontent.com/85092129/141967955-b765c44d-2520-463b-b059-fafdcfc92815.png)

My question is if i can get the video information behind proxy, it is not natural to get the video as well. If the problem is because of proxy, I should not be able to get the video information as well.

Mattermost Enterprise Edition
Behind the firewall, enable modern communication.
Version of  Mattermost : 5.31.1
Database schema version:  5.30.0
Database:  mysql

**Comment by mgdelacroix** [comment]
Hi @TerakoyaAcademia, thanks for the report! Youtube links specifically are not affected by the plugin, you should be able to test this disabling the plugin and sharing a youtube link, it should work in the same way.

**Comment by TerakoyaAcademia** [comment]
@mgdelacroix, Thanks for the reply. YouTube is not affected by the plugin. However, I wanted to know why other video embed displays the blank screen while the mattermost is behind proxy server. Is there any issue related to proxy server denying such requests? Can you please have a look into the plugin.
